spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://user_db:5432/user_db
    username: bodyashah
    password: UZ^LSG2ffM
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    static-path-pattern: /static/**