spring:

  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: bodyashah
    password: UZ^LSG2ffM

  jpa:

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    password: UZ^LSG2ffM
    user: bodyashah
    url: jdbc:postgresql://localhost:5432/user_db